name: Build and Release Extension

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Release tag (example: v1.0.0)"
                required: true
                type: string

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Build Extension
              run: npx web-ext build --source-dir src --artifacts-dir artifacts

            - name: Convert package to XPI
              id: ext
              shell: bash
              run: |
                  EXT_FILE=$(find artifacts -name "*.zip" | head -n 1)

                  if [ -z "$EXT_FILE" ]; then
                    echo "No extension package found!"
                    exit 1
                  fi

                  mv "$EXT_FILE" artifacts/google_language_lock.xpi

                  echo "path=artifacts/google_language_lock.xpi" >> "$GITHUB_OUTPUT"

            - name: Create release archive
              shell: bash
              run: |
                  mkdir package

                  cp "${{ steps.ext.outputs.path }}" package/
                  cp LICENSE package/

                  cd package

                  zip -r "../Google_Language_Lock_${{ github.event.inputs.tag }}.zip" .

            - name: Upload to Mozilla Add-ons
              env:
                  WEB_EXT_API_KEY: ${{ secrets.AMO_JWT_ISSUER }}
                  WEB_EXT_API_SECRET: ${{ secrets.AMO_JWT_SECRET }}
              run: |
                npx web-ext sign \
                  --channel unlisted \
                  --api-key "$WEB_EXT_API_KEY" \
                  --api-secret "$WEB_EXT_API_SECRET" \
                  --source-dir src

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.event.inputs.tag }}
                  generate_release_notes: true
                  files: |
                      Google_Language_Lock_${{ github.event.inputs.tag }}.zip
